version: '2'

services:
   dbhost:
     image: phplist/testdata:medium
     restart: always

   mailhost:
     image: phplist/postfix:latest
     restart: always
     volumes:
       - mailhost_spool:/var/spool/postfix

   phplist-dev:
     depends_on:
       - dbhost
       - mailhost
     image: phplist/phplist:latest
     volumes:
       - /home/michiel/dev/phplist3/public_html/:/var/www/phpList3/public_html/
       - images:/var/www/phpList3/public_html/images
       - /home/michiel/dev/phpListThemes:/var/www/phpList3/public_html/lists/admin/ui/
       - /home/michiel/dev/phpListPlugins:/var/www/phpList3/public_html/lists/admin/plugins/
     ports:
       - "8000:80"
     restart: always
     environment:
       DB_HOST: dbhost
       DB_USER: phplist
       DB_PASSWORD: phplist
       DB_NAME: phplistdb
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: mailhost

   phplist-hosted:
     depends_on:
       - dbhost
       - mailhost
     image: phplist/phplist:latest
     volumes:
       - /home/michiel/hosted-phpList/phpList3/public_html/:/var/www/phpList3/public_html/
       - images:/var/www/phpList3/public_html/images
       - /home/michiel/hosted-phpList/plugins:/var/www/phpList3/public_html/lists/admin/plugins/
     ports:
       - "8001:80"
     restart: always
     environment:
       DB_HOST: dbhost
       DB_USER: phplist
       DB_PASSWORD: phplist
       DB_NAME: phplistdb
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: mailhost

   proxy:
     depends_on:
       - phplist-dev
       - phplist-hosted
     image: proxy:latest
     restart: always
     ports:
       - 80:80
     volumes:
       - /home/michiel/central/:/var/www/html/


volumes:
    images:
    mailhost_spool:
