version: '2'

services:
   dbhost:
     image: phplist/testdata:medium
     restart: always

   mailhost:
     image: phplist/postfix:latest
     volumes:
       - mailhost_spool:/var/spool/postfix

   phplist:
     depends_on:
       - dbhost
       - mailhost
     image: phplist/phplist:latest
     volumes:
       - ${CODE_PATH}:/var/www/phpList3/public_html/
       - images:/var/www/phpList3/public_html/images
       - ${THEME_DEV_PATH}:/var/www/phpList3/public_html/lists/admin/ui/
       - ${PLUGIN_DEV_PATH}:/var/www/phpList3/public_html/lists/admin/plugins/
     ports:
       - "${PORT}:80"
     restart: always
     environment:
       DB_HOST: dbhost
       DB_USER: phplist
       DB_PASSWORD: phplist
       DB_NAME: phplistdb
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: mailhost

volumes:
    images:
    mailhost_spool:
