version: '3'

services:
   dbhost:
     image: mariadb:10.1
     volumes:
       - dbhost_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   mailhost:
     image: phplist/postfix:latest
     volumes:
       - mailhost_spool:/var/spool/postfix

   phplist:
     depends_on:
       - dbhost
       - mailhost
     image: phplist/phplist:3.3.4
     volumes:
       - images:/var/www/phpList3/public_html/images
     ports:
       - "${PORT}:80"
     restart: always
     environment:
       DB_HOST: dbhost
       DB_USER: ${MYSQL_USER}
       DB_PASSWORD: ${MYSQL_PASSWORD}
       DB_NAME: ${MYSQL_DATABASE}
       ADMIN_NAME: ${PHPLIST_ADMINNAME}
       ADMIN_PASSWORD: ${PHPLIST_ADMINPASSWORD}
       ADMIN_EMAIL: ${PHPLIST_ADMINEMAIL}
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: mailhost

volumes:
    dbhost_data:
    images:
    mailhost_spool:
