version: '3.5'

services:
   dbhost:
     container_name: phplist_dbhost
     image: mariadb:10.1
     volumes:
       - dbhost_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   mailhog:
     container_name: phplist_mailhog
     image: mailhog/mailhog:latest
     ports:
       - 8025:8025

   phplist:
     container_name: phplist
     depends_on:
       - dbhost
       - mailhog
     image: phplist/phplist:${PHPLIST_VERSION:-latest}
     volumes:
       - ${IMAGES:-images}:/var/www/phpList3/public_html/images
     ports:
       - "${PORT:-8000}:80"
     restart: always
     environment:
       DB_HOST: dbhost
       DB_USER: ${MYSQL_USER}
       DB_PASSWORD: ${MYSQL_PASSWORD}
       DB_NAME: ${MYSQL_DATABASE}
       ADMIN_NAME: ${PHPLIST_ADMINNAME}
       ADMIN_PASSWORD: ${PHPLIST_ADMINPASSWORD}
       ADMIN_EMAIL: ${PHPLIST_ADMINEMAIL}
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: mailhog

volumes:
    dbhost_data:
    images:
    mailhost_spool:
    plugins:
