
## setup for phpList development

version: '3.5'

networks:
 default:
  ipam:
   driver: default
   config:
   - subnet: 172.18.0.0/16

services:
   dbhost:
     image: phplist/testdata:medium
     environment:
       MYSQL_ROOT_PASSWORD: phplist
     restart: always

   mailhost:
     image: phplist/postfix:latest
     restart: always
     volumes:
       - mailhost_spool:/var/spool/postfix

   mailhog:
     image: mailhog/mailhog:latest
     ports:
       - 8025:8025

   phplist:
     depends_on:
       - dbhost
       - mailhost
     image: phplist/phplist:latest
     build: ./phplist
     volumes:
       - ${CODE_PATH}:/var/www/phpList3/public_html/
       - images:/var/www/phpList3/public_html/images
       - ${THEME_DEV_PATH}:/var/www/phpList3/public_html/lists/admin/ui/
       - ${PLUGIN_DEV_PATH}:/var/www/phpList3/public_html/lists/admin/plugins/
     ports:
       - "${PORT}:80"
     restart: always
     environment:
       DB_HOST: dbhost
       DB_USER: phplist
       DB_PASSWORD: phplist
       DB_NAME: phplistdb
       HOSTNAME: ${HOSTNAME}
       PORT: ${PORT}
       MAILHOST: mailhog

volumes:
    images:
    mailhost_spool:
